DO $VERSION$ BEGIN
	IF env.is_clean() THEN
		DROP SCHEMA IF EXISTS public CASCADE;
		DROP SCHEMA IF EXISTS security CASCADE;
		DROP SCHEMA IF EXISTS social CASCADE;
		DROP SCHEMA IF EXISTS mesh CASCADE;
		DROP SCHEMA IF EXISTS test CASCADE;
		
		CREATE SCHEMA public;
	END IF;
END $VERSION$;
